import { Activity, AlertTriangle, BatteryMedium, Moon, Zap } from 'lucide-react';
import { AppShell } from '@/components/nexo/app-shell';
import { Badge } from '@/components/ui/badge';
import { Card, CardAction, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';

export default function LoadPage() {
  return <AppShell active="carga"><div className="mx-auto max-w-[1200px] px-5 py-8 sm:px-7 lg:px-9"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">Monitoreo descriptivo</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Carga y bienestar</h1><p className="mt-1 text-sm text-muted-foreground">Señales para revisar con el cuerpo técnico, sin diagnósticos automáticos.</p></div><div className="mt-6 grid gap-4 md:grid-cols-3"><Wellness icon={BatteryMedium} label="Energía promedio" value="7,4 / 10" progress={74} /><Wellness icon={Moon} label="Sueño promedio" value="7 h 18 min" progress={81} /><Wellness icon={Activity} label="PSE semanal" value="6,2" progress={62} /></div><Card className="mt-4 border-none bg-card ring-1 ring-border"><CardHeader><CardTitle className="text-[15px] font-bold">Señales a revisar</CardTitle><CardDescription>Combinaciones recientes de carga, bienestar y actividad</CardDescription><CardAction><Badge variant="outline" className="border-[#ead4a1] bg-[#fff8e8] text-[#876016]">4 casos</Badge></CardAction></CardHeader><CardContent className="space-y-2">{['Lucía Méndez · PSE por encima del objetivo', 'Tomás Silva · Molestia repetida en hombro', 'Martina Ruiz · Actividad incompleta', 'Nicolás Rojas · Sueño bajo durante 3 días'].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl border border-border p-3"><span className="grid size-8 place-items-center rounded-lg bg-[#fff5dc] text-[#9a6b12]"><AlertTriangle className="size-3.5" /></span><p className="flex-1 text-sm font-medium">{item}</p><Badge variant="outline">Revisar</Badge></div>)}</CardContent></Card></div></AppShell>;
}

function Wellness({ icon: Icon, label, value, progress }: { icon: typeof Zap; label: string; value: string; progress: number }) { return <Card className="border-none bg-card ring-1 ring-border"><CardHeader><CardDescription>{label}</CardDescription><CardAction className="grid size-8 place-items-center rounded-lg bg-[#edf4e1] text-[#52751d]"><Icon className="size-4" /></CardAction></CardHeader><CardContent><p className="text-xl font-bold">{value}</p><Progress value={progress} className="mt-4 [&_[data-slot=progress-indicator]]:bg-[#9fcf2d]" /></CardContent></Card>; }
